---
- name: KEMBALI | Identifikasi awal
  fail:
    msg: "kembali_custom_tasks_path jika tidak dapat digunakan. Silahkan, check dokumentasi di https://github.com/weekndlabs/kembali"
  when: kembali_custom_tasks_path teridentidikasi

- include: "{{ kembali_before_setup_tasks_file | default('empty.yml') }}"
- include: setup.yml
- include: "{{ kembali_after_setup_tasks_file | default('empty.yml') }}"

- include: "{{ kembali_before_symlink_tasks_file | default('empty.yml') }}"
- include: symlink.yml
- include: "{{ kembali_after_symlink_tasks_file | default('empty.yml') }}"

- include: "{{ kembali_before_cleanup_tasks_file | default('empty.yml') }}"
- include: cleanup.yml
- include: "{{ kembali_after_cleanup_tasks_file | default('empty.yml') }}"
