---
- name: KEMBALI | Mendapatkan path rilis
  command: echo "{{ kembali_deploy_to }}/{{ kembali_version_dir }}"
  register: kembali_releases_path

- name: KEMBALI | Mendapatkan num serial untuk rilis
  shell: echo `ls -1t {{ kembali_releases_path.stdout }} | wc -l`
  register: kembali_versions_count

- name: KEMBALI | Memeriksa apakah ada lebih dari saru rilis
  fail:
    msg: "Tidak dapat mengembalikan kode karena tidak ada rilis sebelumnya"
  when: kembali_versions_count.stdout|int <= 1

- name: KEMBALI | Mendapatkan versi rilis saat ini
  shell: echo `ls -1t {{ kembali_releases_path.stdout }} | head -n 1`
  register: kembali_current_release_version

- stat:
    path: "{{ kembali_releases_path.stdout }}/{{ kembali_rollback_to_release }}"
  register: stat_rollback_release_version
  when: kembali_rollback_to_release != ""

- name: KEMBALI | Memeriksa apakah rilis rollback tersedia
  fail:
    msg: "Versi rollback tidak ada"
  when: kembali_rollback_to_release != "" and (stat_rollback_release_version.stat.exists is not defined or stat_rollback_release_version.stat.isdir == False)

- name: KEMBALI | Mendapatkan versi rilis sebelumnya
  shell: echo `ls -1t {{ kembali_releases_path.stdout }} | head -n 2 | tail -n 1`
  register: kembali_previous_release_version

- name: KEMBALI | Mendapatkan versi rilis rollback
  set_fact:
    kembali_rollback_release_version: "{{ kembali_rollback_to_release if kembali_rollback_to_release != '' else kembali_previous_release_version.stdout }}"

- name: KEMBALI | Mendapatkan path rilis
  command: echo "{{ kembali_releases_path.stdout }}/{{ kembali_rollback_release_version }}"
  register: kembali_release_path
