---
- name: ANSISTRANO | Change symlink from current release to a previous one
  file:
    state: link
    path: "{{ kembali_deploy_to }}/{{ kembali_current_dir }}"
    src: "./{{ kembali_version_dir }}/{{ kembali_rollback_release_version }}"
